### ISSUE TITLE
.validate throwing error

### ISSUE THREAD

**Issue by samjbmason** [dthree/vorpal#110]
I have a vorpal command that looks like this:
I am running version 1.9.5.

```js
vorpal
   .command('temp [dev]')
   .validate(function() {
     return false
   })
   .action(function() {
     ...
   })

vorpal.parse(process.argv)
```

And when i run `pnt temp` in my terminal I get this error thrown:

```js
/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:169
          throw new Error(err);
          ^

Error: null
    at EventEmitter.<anonymous> (/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:169:17)
    at callback (/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:830:22)
    at /Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:961:7
    at EventEmitter._commandSetCallback (/Users/samm/Sites/pnt/node_modules/vorpal/dist/session.js:446:5)
    at EventEmitter.session.completeCommand (/Users/samm/Sites/pnt/node_modules/vorpal/dist/session.js:526:12)
    at onCompletion (/Users/samm/Sites/pnt/node_modules/vorpal/dist/session.js:456:10)
    at EventEmitter.session.execCommandSet (/Users/samm/Sites/p nt/node_modules/vorpal/dist/session.js:471:5)
    at EventEmitter.vorpal._exec (/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:960:18)
    at EventEmitter.vorpal._execQueueItem (/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:751:17)
    at EventEmitter.vorpal._queueHandler (/Users/samm/Sites/pnt/node_modules/vorpal/dist/vorpal.js:735:10)
```

**Comment by dthree** [comment]
Thanks.

Fixed in `v1.10.8`.
