### ISSUE TITLE
"undefined" and .catch

### ISSUE THREAD

**Issue by devsnek** [dthree/vorpal#197]
if i put in some text that will be handled by vorpal.catch, and it contains "undefined", this error is thrown

```
> this is undefined
readline.js:983
            throw err;
            ^

Error: vorpal._exec was called with an undefined command.
    at Vorpal.vorpal._exec (node_modules/vorpal/dist/vorpal.js:787:11)
    at Vorpal.vorpal._execQueueItem (node_modules/vorpal/dist/vorpal.js:751:17)
    at Vorpal.vorpal._queueHandler (node_modules/vorpal/dist/vorpal.js:735:10)
    at Vorpal.vorpal.exec (node_modules/vorpal/dist/vorpal.js:682:10)
    at node_modules/vorpal/dist/vorpal.js:625:10
    at module.exports.completed (node_modules/vorpal/dist/ui.js:219:13)
    at module.exports.PromptUI.onCompletion (node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.onCompleted (node_modules/rx-lite/rx.lite.js:5871:19)
```

**Comment by noambenami** [comment]
Why was this ticket closed with no comments? I'm being affected by this ATM...

**Comment by jcar787** [comment]
I'm having this issue too.
Is there any solution on how to avoid this?

**Comment by jcar787** [comment]
In my case if I have the word undefined in one of my commands this triggers the issue. I don't know if that helps somehow to debug it.

**Comment by noambenami** [comment]
Looking at the commit history here, it is clear that this project is dead.
