### ISSUE TITLE
Cannot run tests on current master -> Cannot find module '../dist/vorpal'

### ISSUE THREAD

**Issue by fkretzer** [dthree/vorpal#271]
-> git clone
-> yarn
-> yarn test

`Error: Cannot find module '../dist/vorpal'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/foobar/development/vorpal/test/autocomplete.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/foobar/development/vorpal/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/foobar/development/vorpal/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/foobar/development/vorpal/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/foobar/development/vorpal/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.`

**Comment by milesj** [comment]
Master is currently in development for v2.

**Comment by milesj** [comment]
I moved the 2.0 code to a branch and reset master to the last commit before 2.0 work.

**Comment by fkretzer** [comment]
Thx, i will wait until the test-suite is fixed on the 2.0 branch then before i try to reproduce the bug i wanted to report :-) Keep up the good work!
