### ISSUE TITLE
Please release. Examples do not work with latest release

### ISSUE THREAD

**Issue by johncblandii** [dthree/vorpal#301]
I'm attempting to use title, version, and banner from examples (like https://github.com/dthree/vorpal/blob/master/examples/descriptors/descriptors.js). 

```
  .title(chalk.magenta('Vorpal'))
   ^

TypeError: vorpal.title is not a function
    at Object.<anonymous> (/mycode/index.js:10:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

These methods exist in master. Can we get a release?

**Comment by johncblandii** [comment]
@dthree @milesj thoughts here? Can we get a quick NPM push and github release?

**Comment by milesj** [comment]
Sorry, I don't have access to release.

**Comment by johncblandii** [comment]
Ah, ok. I saw you floating around some issues and joining in (possibly taking over repo) so figured I'd check.

**Comment by johncblandii** [comment]
![beuller](https://media.giphy.com/media/MkxZKy77sWoEw/giphy.gif)

**Comment by johncblandii** [comment]
I'm starting to think @dthree has turned off notifications.

**Comment by parro-it** [comment]
No, if you look at the repo watchers, he's still there. But maybe is busy with other projects or real life things...

**Comment by johncblandii** [comment]
I'm well aware, @parro-it. I come back ever so often to get a new notification in hopes they actually maintain it, turn over the project to someone else, or at least push the latest to NPM.

**Comment by sundowndev** [comment]
Still relevant. Please fix.

For some reasons, the NPM package version is different than the repo version. The last publication was 2 years ago.

Solutions : 
- install the package using git repo
- fork and make your own, [I published mine](https://www.npmjs.com/package/vorpax), this is the exact same package but npm repository is sync with git
