### ISSUE TITLE
After executing command I am getting this issue(not using vorpal prompt)

### ISSUE THREAD

**Issue by hiteshbalraw** [dthree/vorpal#59]
vorpal
        .command('connect [username] [password]')
        .description('Connect to server.')
        .action(function (args, callback) {
            setTimeout(function () {
                // deleting options key from args
                delete args.options;
    
                var context = domain.create();
    
                // error handling in domain
                context.on('error', errorHandler);
    
                // running the connect in domain
                context.run(function() {
                    console.log("Arguments : ", args);
                });
            }, 0);
        });
    
    vorpal
        .delimiter('hdb$')
        .show();

Vorpal Prompt error: TypeError: Cannot read property 'setRawMode' of null
    at ReadStream.setRawMode (tty.js:67:15)
    at Interface._setRawMode (readline.js:177:23)
    at new Interface (readline.js:137:10)
    at Object.exports.createInterface (readline.js:39:10)
    at Object.Interface.createInterface (/home/users/my-cli/node_modules/vorpal/node_modules/inquirer/node_modules/readline2/index.js:34:21)
    at module.exports (/home/users/my-cli/node_modules/vorpal/node_modules/inquirer/lib/ui/baseUI.js:14:30)
    at new module.exports (/home/users/my-cli/node_modules/vorpal/node_modules/inquirer/lib/ui/prompt.js:15:8)
    at Object.promptModule [as prompt] (/home/users/my-cli/node_modules/vorpal/node_modules/inquirer/lib/inquirer.js:27:14)
    at Object.ui.prompt (/home/users/my-cli/node_modules/vorpal/lib/ui.js:171:25)
    at EventEmitter.vorpal._prompt (/home/users/my-cli/node_modules/vorpal/lib/vorpal.js:528:15)
    at EventEmitter.<anonymous> (/home/users/my-cli/node_modules/vorpal/lib/vorpal.js:542:12)
    at callback (/home/users/my-cli/node_modules/vorpal/lib/vorpal.js:705:22)
    at /home/users/my-cli/node_modules/vorpal/lib/vorpal.js:824:7
    at EventEmitter._commandSetCallback (/home/users/my-cli/node_modules/vorpal/lib/session.js:455:5)
    at EventEmitter.session.completeCommand (/home/users/my-cli/node_modules/vorpal/lib/session.js:519:12)
    at onCompletion (/home/users/my-cli/node_modules/vorpal/lib/session.js:465:10)

Please let me know if I am doing something wrong in this.

**Comment by dthree** [comment]
Thanks. Could you please post this as a [StackOverflow](http://stackoverflow.com/questions/tagged/vorpal.js) question? In this way, I can help others with an answer as well.

**Comment by hiteshbalraw** [comment]
​Hi Team,

http://stackoverflow.com/questions/34304036/after-successful-execution-of-vorpal-command-error-is-thrown
​

Please look into it ASAP.

Thanks.

Hitesh Baldaniya
Application Engineer | *@builtio*

**Comment by dthree** [comment]
Thanks!
